### ISSUE TITLE
[Testing Party] Upload a Question

### ISSUE THREAD

**Issue by xiaolin-zhong** [gcivil-nyu-org/INET-Wednesday-Spring2023-Team-3#134]
I was able to upload a question with the following fields:

![image.png](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/803478b4-fdd4-4ec0-8383-c9a9c28eaa2f)image.png

1. Position can be just a single char num input.
2. It did not require me to fill out the difficulty & type filters. So this question cannot be found via filters but can be found through the search bar. Seems like type defaults to 'Coding' anyway if nothing was inputted.
3. Not sure what category input field is suppose to be, but also allowed me to leave it blank.
4. After clicking submit, fields don't empty so I tried clicking submit again. Same pop up that the "Question has been uploaded successfully" despite it being a duplicate. But it looks like it not actually uploaded since I couldn't find it.
5. When opening the question I created, there's no option to record, upload my answer or write code.
![image.png](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/eea60b59-a4cb-47c4-a48c-b3fc1e3c3d73)

'Not satisfied' options in the difficulty and type filters. Maybe it was suppose to act as 'None' but perhaps don't allow that?
![image.png](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/4ed8d4a7-306a-4ee7-845b-aeeea8e716e3)

**Comment by zhujiumu** [comment]
1. no input validations for position - since position name can be any string, we are relying on the users to make sure their submissions are meaningful. 
2. difficulty is optional, and yes leaving the type section empty will default to coding. 
3. category is a supplementary info for the question, i.e. someone can put in "sliding window"
4. yes our backend checks for duplicate entries, we will implement something on the frontend to let the user know it's a duplicate.
5. we will work on a fix for this one - thank you!
